// Derived from Citrix ADC Nitro Go SDK (https://github.com/netscaler/adc-nitro-go)
// Originally licensed under the Apache License, Version 2.0
// Modifications by Adam Crawford, 2025

package models

type LBVServer struct {
	ADFSProxyProfile                   string `json:"adfsproxyprofile,omitempty"`
	APIProfile                         string `json:"apiprofile,omitempty"`
	AppFlowLog                         string `json:"appflowlog,omitempty"`
	Authentication                     string `json:"authentication,omitempty"`
	AuthenticationHost                 string `json:"authenticationhost,omitempty"`
	Authn401                           string `json:"authn401,omitempty"`
	AuthnProfile                       string `json:"authnprofile,omitempty"`
	AuthnVSName                        string `json:"authnvsname,omitempty"`
	BackupLBMethod                     string `json:"backuplbmethod,omitempty"`
	BackupPersistenceTimeout           int    `json:"backuppersistencetimeout,omitempty"`
	BackupVServer                      string `json:"backupvserver,omitempty"`
	BypassAAAA                         string `json:"bypassaaaa,omitempty"`
	Cacheable                          string `json:"cacheable,omitempty"`
	CltTimeOut                         string `json:"clttimeout,omitempty"`
	Comment                            string `json:"comment,omitempty"`
	ConnFailOver                       string `json:"connfailover,omitempty"`
	CookieName                         string `json:"cookiename,omitempty"`
	DataLength                         string `json:"datalength,omitempty"`
	DataOffset                         string `json:"dataoffset,omitempty"`
	DbProfileName                      string `json:"dbprofilename,omitempty"`
	DbsLB                              string `json:"dbslb,omitempty"`
	DisablePrimaryOnDown               string `json:"disableprimaryondown,omitempty"`
	DNS64                              string `json:"dns64,omitempty"`
	DNSOverHTTPS                       string `json:"dnsoverhttps,omitempty"`
	DNSProfileName                     string `json:"dnsprofilename,omitempty"`
	DownStateFlush                     string `json:"downstateflush,omitempty"`
	HashLength                         int    `json:"hashlength,omitempty"`
	HealthThreshold                    string `json:"healththreshold,omitempty"`
	HTTPProfileName                    string `json:"httpprofilename,omitempty"`
	HTTPSRedirectURL                   string `json:"httpsredirecturl,omitempty"`
	ICMPVSRresponse                    string `json:"icmpvsrresponse,omitempty"`
	InsertVServerIPPort                string `json:"insertvserveripport,omitempty"`
	IPMask                             string `json:"ipmask,omitempty"`
	IPPattern                          string `json:"ippattern,omitempty"`
	IPSet                              string `json:"ipset,omitempty"`
	IPv46                              string `json:"ipv46,omitempty"`
	L2Conn                             string `json:"l2conn,omitempty"`
	LBMethod                           string `json:"lbmethod,omitempty"`
	LBProfileName                      string `json:"lbprofilename,omitempty"`
	ListenPolicy                       string `json:"listenpolicy,omitempty"`
	ListenPriority                     int    `json:"listenpriority,omitempty"`
	M                                  string `json:"m,omitempty"`
	MACModeRetainVLAN                  string `json:"macmoderetainvlan,omitempty"`
	MaxAutoScaleMembers                string `json:"maxautoscalemembers,omitempty"`
	MinAutoScaleMembers                string `json:"minautoscalemembers,omitempty"`
	MSSQLServerVersion                 string `json:"mssqlserverversion,omitempty"`
	MySQLCharacterSet                  int    `json:"mysqlcharacterset,omitempty"`
	MySQLProtocolVersion               int    `json:"mysqlprotocolversion,omitempty"`
	MySQLServerCapabilities            int    `json:"mysqlservercapabilities,omitempty"`
	MySQLServerVersion                 string `json:"mysqlserverversion,omitempty"`
	Name                               string `json:"name,omitempty"`
	Netmask                            string `json:"netmask,omitempty"`
	NetProfile                         string `json:"netprofile,omitempty"`
	NewName                            string `json:"newname,omitempty"`
	NewServiceRequest                  int    `json:"newservicerequest,omitempty"`
	NewServiceRequestIncrementInterval int    `json:"newservicerequestincrementinterval,omitempty"`
	NewserviceRequestUnit              string `json:"newservicerequestunit,omitempty"`
	OracleServerVersion                string `json:"oracleserverversion,omitempty"`
	Order                              int    `json:"order,omitempty"`
	OrderThreshold                     string `json:"orderthreshold,omitempty"`
	PersistAVPNO                       []int  `json:"persistavpno,omitempty"`
	PersistenceBackup                  string `json:"persistencebackup,omitempty"`
	PersistenceType                    string `json:"persistencetype,omitempty"`
	PersistMask                        string `json:"persistmask,omitempty"`
	Port                               int    `json:"port,omitempty"`
	ProbePort                          int    `json:"probeport,omitempty"`
	ProbeProtocol                      string `json:"probeprotocol,omitempty"`
	ProbeSuccessResponsecode           string `json:"probesuccessresponsecode,omitempty"`
	ProcessLocal                       string `json:"processlocal,omitempty"`
	Push                               string `json:"push,omitempty"`
	PushLabel                          string `json:"pushlabel,omitempty"`
	PushMultiClients                   string `json:"pushmulticlients,omitempty"`
	PushVServer                        string `json:"pushvserver,omitempty"`
	QUICBridgeProfileName              string `json:"quicbridgeprofilename,omitempty"`
	QUICProfileName                    string `json:"quicprofilename,omitempty"`
	Range                              string `json:"range,omitempty"`
	RecursionAvailable                 string `json:"recursionavailable,omitempty"`
	RedirectFromPort                   int    `json:"redirectfromport,omitempty"`
	RedirectPortRewrite                string `json:"redirectportrewrite,omitempty"`
	RedirURL                           string `json:"redirurl,omitempty"`
	RedirURLFlags                      bool   `json:"redirurlflags,omitempty"`
	Resrule                            string `json:"resrule,omitempty"`
	RetainConnectionsonCluster         string `json:"retainconnectionsoncluster,omitempty"`
	RHIState                           string `json:"rhistate,omitempty"`
	RTSPNAT                            string `json:"rtspnat,omitempty"`
	Rule                               string `json:"rule,omitempty"`
	ServiceName                        string `json:"servicename,omitempty"`
	ServiceType                        string `json:"servicetype,omitempty"`
	Sessionless                        string `json:"sessionless,omitempty"`
	SkipPersistency                    string `json:"skippersistency,omitempty"`
	SoBackupAction                     string `json:"sobackupaction,omitempty"`
	SoMethod                           string `json:"somethod,omitempty"`
	SoPersistence                      string `json:"sopersistence,omitempty"`
	SoPersistenceTimeout               string `json:"sopersistencetimeout,omitempty"`
	SoThreshold                        int    `json:"sothreshold,omitempty"`
	State                              string `json:"state,omitempty"`
	TCPProbePort                       int    `json:"tcpprobeport,omitempty"`
	TCPProfileName                     string `json:"tcpprofilename,omitempty"`
	Td                                 string `json:"td,omitempty"`
	Timeout                            int    `json:"timeout,omitempty"`
	ToggleOrder                        string `json:"toggleorder,omitempty"`
	TOSID                              int    `json:"tosid,omitempty"`
	TROFSPersistence                   string `json:"trofspersistence,omitempty"`
	V6NetMaskLen                       int    `json:"v6netmasklen,omitempty"`
	V6PersistMaskLen                   string `json:"v6persistmasklen,omitempty"`
	VIPHeader                          string `json:"vipheader,omitempty"`
	Weight                             int    `json:"weight,omitempty"`

	ActiveAervices            string `json:"activeservices,omitempty"`
	BackupvAerverAtatus       string `json:"backupvserverstatus,omitempty"`
	BindPoint                 string `json:"bindpoint,omitempty"`
	CacheVServer              string `json:"cachevserver,omitempty"`
	ConsolidatedLConn         string `json:"consolidatedlconn,omitempty"`
	ConsolidatedLConngbl      string `json:"consolidatedlconngbl,omitempty"`
	CookieDomain              string `json:"cookiedomain,omitempty"`
	CurrentactiveOrder        string `json:"currentactiveorder,omitempty"`
	CurState                  string `json:"curstate,omitempty"`
	DNSVServerName            string `json:"dnsvservername,omitempty"`
	Domain                    string `json:"domain,omitempty"`
	EffectiveState            string `json:"effectivestate,omitempty"`
	GroupName                 string `json:"groupname,omitempty"`
	Gt2GB                     string `json:"gt2gb,omitempty"`
	Health                    string `json:"health,omitempty"`
	Homepage                  string `json:"homepage,omitempty"`
	IPMapping                 string `json:"ipmapping,omitempty"`
	IsGLSB                    bool   `json:"isgslb,omitempty"`
	LBRRReason                int    `json:"lbrrreason,omitempty"`
	Map                       string `json:"map,omitempty"`
	NextGenAPIResource        string `json:"_nextgenapiresource,omitempty"`
	NGName                    string `json:"ngname,omitempty"`
	NodeFaultBindings         string `json:"nodefaultbindings,omitempty"`
	Precedence                string `json:"precedence,omitempty"`
	Redirect                  string `json:"redirect,omitempty"`
	Ruletype                  string `json:"ruletype,omitempty"`
	StateChangeTimeMsec       string `json:"statechangetimemsec,omitempty"`
	StateChangeTimeSec        string `json:"statechangetimesec,omitempty"`
	StateChangeTimeSeconds    string `json:"statechangetimeseconds,omitempty"`
	Status                    int    `json:"status,omitempty"`
	ThresholdValue            int    `json:"thresholdvalue,omitempty"`
	TicksSinceLastStateChange string `json:"tickssincelaststatechange,omitempty"`
	TotalServices             string `json:"totalservices,omitempty"`
	Type                      string `json:"type,omitempty"`
	Value                     string `json:"value,omitempty"`
	Version                   int    `json:"version,omitempty"`
	VSvrDynConnsoThreshold    string `json:"vsvrdynconnsothreshold,omitempty"`
}

type LBVServerServiceGroupMemberBinding struct {
	CookieIPPort      string `json:"cookieipport,omitempty"`
	CookieName        string `json:"cookiename,omitempty"`
	CurState          string `json:"curstate,omitempty"`
	DynamicWeight     string `json:"dynamicweight,omitempty"`
	Ipv46             string `json:"ipv46,omitempty"`
	Name              string `json:"name,omitempty"`
	Order             int    `json:"order,omitempty"`
	OrderStr          string `json:"orderstr,omitempty"`
	PreferredLocation string `json:"preferredlocation,omitempty"`
	Port              int    `json:"port,omitempty"`
	ServiceGroupName  string `json:"servicegroupname,omitempty"`
	ServiceType       string `json:"servicetype,omitempty"`
	VServerid         string `json:"vserverid,omitempty"`
	Weight            string `json:"weight,omitempty"`
}
